# Generated by Django 2.2.14 on 2020-07-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, default='', max_length=60)),
                ('emailAddress', models.EmailField(blank=True, default='', max_length=60)),
                ('password', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chainId', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('subject', models.CharField(blank=True, default='', max_length=60)),
                ('body', models.CharField(blank=True, default='', max_length=300)),
                ('recipientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='MessagingApp.User')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='MessagingApp.User')),
            ],
        ),
    ]
