# Generated by Django 2.2.14 on 2020-07-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingApp', '0004_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
